language: ruby
rvm:
  - 2.2.0

before_install:
  - gem install bundler

services:
  - mongodb

before_script:
  - sleep 15
  - mongo mongoid_fixtures_development --eval 'db.addUser("travis", "test");'
